service: default
# service: service-artemis
runtime: python27
api_version: 1
threadsafe: true
env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'true'
libraries:
- name: ssl
  version: latest
- name: lxml
  version: latest


handlers:
- url: /static
  static_dir: static
- url: /.*
  script: server.app

